zar-10-add-product-entity
Mike-Opanasiuk/ItStep_Exam_eCommerce pull request #8
Opened 2022-06-15 08:02 UTC by Sidanton6006

2022-06-15 08:56 UTC, Mike-Opanasiuk approved these changes, later dismissed
Code review done

2022-06-15 09:05 UTC, byCodeXp requested changes
- Product entity musy be named as ProductEntity
- Fields Name, Price, Description of ProductEntity must have get and set properties.
- You should add configuration for "Product" entity.

2022-06-16 09:53 UTC, byCodeXp approved these changes
Looks good

2022-06-20 11:22 UTC, Mike-Opanasiuk requested changes
Make ProductEnity **Name** field optional. Add migration after adding an entity.

2022-06-20 11:22 UTC, Mike-Opanasiuk commented on Core/Entities/Product.cs
> +    public double Price;
Change price type to decimal. Double type provides less precise way to save data.

2022-06-21 14:25 UTC, Mike-Opanasiuk approved these changes

2022-06-22 07:15 UTC, merged