Zar 11 add category entity
Mike-Opanasiuk/ItStep_Exam_eCommerce pull request #9
Opened 2022-06-22 08:51 UTC by Sidanton6006

2022-06-22 08:55 UTC, Mike-Opanasiuk commented on Core/Entities/CategoryEntity.cs
> +    public Guid? ParentId { get; set; }
Rename to ParentCategoryId

2022-06-22 09:08 UTC, byCodeXp requested changes
📛 Use Guid instead of int type for CategoryId in ProductEntity.cs

2022-06-22 09:09 UTC, Mike-Opanasiuk requested changes
Request changes

2022-06-27 05:19 UTC, Mike-Opanasiuk approved these changes
Well done!

2022-06-27 13:18 UTC, byCodeXp approved these changes
Ok

2022-06-27 13:18 UTC, merged